name: "Code for Life - GCloud - Setup"
description: "Set up the GCloud CLI."
runs:
  using: composite
  steps:
    - name: 🗝 Authenticate with GCloud
      uses: google-github-actions/auth@v2
      with:
        project_id: 'decent-digit-629'
        workload_identity_provider: 'projects/354656325390/locations/global/workloadIdentityPools/cfl-pool/providers/cfl-provider'
        service_account: 'github-actions-34@decent-digit-629.iam.gserviceaccount.com'

    - name: 🤖 Set up GCloud SDK
      uses: google-github-actions/setup-gcloud@v3
