name: "Code for Life - Prettier - Check Format"
description: "Download all of prettier's config files and run prettier to check the format of the code."
inputs:
  download-branch:
    description: "The branch of the workspace repo to download the config files from."
    required: true
    default: "main"
  save-dir:
    description: "The directory to save the config files to."
    required: true
    default: ".workspace"
  scripts-path:
    description: "The path to the scripts bash file."
    required: true
    default: "./scripts"
runs:
  using: composite
  steps:
    - name: 📥 Download Prettier Config Files
      uses: ocadotechnology/codeforlife-workspace/.github/actions/prettier/download-configs@main
      with:
        download-branch: ${{ inputs.download-branch }}
        save-dir: ${{ inputs.save-dir }}

    - name: 🔎 Check Code Format
      shell: bash
      env:
        WORKSPACE_PRETTIER_CONFIG: ${{ inputs.save-dir }}/.prettierrc.json
        WORKSPACE_PRETTIER_IGNORE: ${{ inputs.save-dir }}/.prettierignore
      run: ${{ inputs.scripts-path }} format:check
