name: "Code for Life - AWS - Create Resources"
description: "Create the AWS resources used in our environment."
inputs:
  # CLI
  region:
    description: "The region of the resources."
    required: true
    default: us-east-1
  access-key-id:
    description: "The ID of the AWS credentials."
    required: true
    default: test
  secret-access-key:
    description: "The secret of the AWS credentials."
    required: true
    default: test
  cli-version:
    description: "The version of the AWS CLI to install."
    required: true
    default: 2.26.1
  # SQS
  sqs-queues:
    description: "A CSV of AWS SQS queues to create."
    required: true
    default: ""
  # S3
  s3-buckets:
    description: "A CSV of AWS S3 buckets to create."
    required: true
    default: ""
  # LocalStack
  localstack-debug:
    description: "Whether LocalStack is in debug mode."
    required: false
    default: "0"
  localstack-version:
    description: "The LocalStack version to set up."
    required: false
    default: "4.3.0"
runs:
  using: composite
  steps:
  # Based on inputs, determine what LocalStack services are required.
  - name: ⚙️ Get LocalStack Services
    id: get-localstack-services
    shell: bash
    run: |
      services=() # Empty string array to append LocalStack service names to.

      # Append service if it has resources.
      function append_service() {
        if [ "$1" != "" ]; then services+=("$2"); fi
      }

      # Convert array to single-line CSV string.
      array_to_csv() {
        local IFS=","
        echo "${services[*]}"
      }

      append_service "${{ inputs.sqs-queues }}" "sqs"
      append_service "${{ inputs.s3-buckets }}" "s3"

      echo "services=$(array_to_csv)" >> $GITHUB_OUTPUT

  - name: 📥 Install AWS CLI
    if: steps.get-localstack-services.outputs.services != ''
    uses: ocadotechnology/codeforlife-workspace/.github/actions/aws/install-cli@main
    with:
      version: ${{ inputs.cli-version }}

  - name: 🚀 Set Up LocalStack
    if: steps.get-localstack-services.outputs.services != ''
    uses: LocalStack/setup-localstack@v0.2.4
    with:
      image-tag: ${{ inputs.localstack-version }}
      install-awslocal: "false"
      configuration: |
        DEBUG=${{ inputs.localstack-debug }}
        SERVICES=${{ steps.get-localstack-services.outputs.services }}
        DEFAULT_REGION=${{ inputs.region }}

  - name: ⚙️ Set Environment Variables
    if: steps.get-localstack-services.outputs.services != ''
    shell: bash
    run: | # Used by AWS CLI.
      echo "AWS_REGION=${{ inputs.region }}" >> $GITHUB_ENV
      echo "AWS_ACCESS_KEY_ID=${{ inputs.access-key-id }}" >> $GITHUB_ENV
      echo "AWS_SECRET_ACCESS_KEY=${{ inputs.secret-access-key }}" >> $GITHUB_ENV
      echo "AWS_ENDPOINT_URL=http://localhost:4566" >> $GITHUB_ENV

  - name: 🏗️ Create SQS Queues
    if: contains(steps.get-localstack-services.outputs.services, 'sqs')
    uses: ocadotechnology/codeforlife-workspace/.github/actions/github/process-values@main
    with:
      values: ${{ inputs.sqs-queues }}
      process: aws sqs create-queue --queue-name="$1"

  - name: 🏗️ Create S3 Buckets
    if: contains(steps.get-localstack-services.outputs.services, 's3')
    uses: ocadotechnology/codeforlife-workspace/.github/actions/github/process-values@main
    with:
      values: ${{ inputs.s3-buckets }}
      process: aws s3api create-bucket --bucket="$1"
