#!/bin/bash

# Exit on error.
set -e

# Change working directory to directory of this script.
cd "${BASH_SOURCE%/*}"

# Delete existing virtual environment.
shopt -s extglob
rm -rf .venv/!(".gitkeep")
shopt -u extglob

# Create new virtual environment.
pipenv install

# Run setup script.
pipenv run python . "$@"
