#!/bin/bash

# A CLI for each backend service.
#  - The 1st arg is the name of the function.
#  - All the remaining args are the arguments of the function.

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

# The path to the backend directory in the workspace.
backend_dir=".workspace/backend"

# The path of the pyproject.toml.
pyproject_toml="$backend_dir/pyproject.toml"

# The path of the source code.
source=${SOURCE:-"."}

export PIPENV_VERBOSITY="${PIPENV_VERBOSITY:--1}"

# Shorthand for the mypy CLI.
# https://mypy.readthedocs.io/en/stable/command_line.html
mypy="pipenv run mypy --config-file=$pyproject_toml"

# Shorthand for the isort CLI.
# https://pycqa.github.io/isort/docs/configuration/options.html
isort="pipenv run isort --settings-file=$pyproject_toml"

# Shorthand for the black CLI.
# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
black="pipenv run black --config=$pyproject_toml"

# Shorthand for the pylint CLI.
# https://pylint.pycqa.org/en/stable/user_guide/configuration/all-options.html
pylint="pipenv run pylint --rcfile=$pyproject_toml"

# Shorthand for the django CLI.
django="pipenv run python manage.py"

# Shorthand for the pytest CLI.
# https://docs.pytest.org/en/8.3.x/reference/reference.html
# https://pytest-xdist.readthedocs.io/en/stable/distribution.html
pytest="pipenv run pytest -c=$pyproject_toml -n=auto"

# ------------------------------------------------------------------------------
# Private/Utility Functions
# ------------------------------------------------------------------------------

function _count_files() { echo "$@" | wc -l; }

function _find_all_files() {
  names="${names:-"*.py"}" find_files \
    -not -path "*/.venv/*" \
    -not -path "*/.workspace/*" \
    -not -path "*/migrations/*" \
    $@
}

function _find_test_files() { names="*_test.py" _find_all_files $@; }

function _find_non_test_files() { _find_all_files -not -name "*_test.py" $@; }

function _pipe_files_to_cli() {
  echo_cmd "$@"
  find_files="_find_${find_files:-"all"}_files" pipe_files_to_cli $@
}

function _make_pytest_options() {
  local options="$@"

  if ! eval_bool "${DJANGO:-1}"; then options+=" -p no:django"; fi

  # https://pytest-cov.readthedocs.io/en/latest/config.html
  if eval_bool "${coverage:-0}"; then options+=" --cov=$source"; fi

  echo "$options"
}

# ------------------------------------------------------------------------------
# Public/Callable Functions
# ------------------------------------------------------------------------------

function setup() {
  # Setup your local environment.
  echo_and_run_cmd pipenv install --dev
}

function hard_install() {
  function cleanup() {
    if [ -f "Pipfile.lock" ]; then echo "Deleting Pipfile.lock"; fi
    echo_and_run_cmd rm -f Pipfile.lock

    if [ -e ".venv" ]; then echo "Deleting .venv"; fi
    echo_and_run_cmd rm -rf .venv
    echo_and_run_cmd mkdir .venv
    echo_and_run_cmd touch .venv/.gitkeep
  }

  callback="cleanup" step Cleaning up PY environment
  callback="setup" step Setting up PY environment
  return $exit_code
}

function imports:check() {
  # Check imports order.
  _pipe_files_to_cli $isort --check
}

function format() {
  # Format code.
  _pipe_files_to_cli $black
}

function format:check() {
  # Check formatting issues.
  _pipe_files_to_cli $black --check
}

function types:check() {
  # Check static types.
  _pipe_files_to_cli $mypy
}

function code:check:non_tests {
  # Find linting issues in non-test files.
  find_files="non_test" _pipe_files_to_cli $pylint
}

function code:check:tests() {
  # Find linting issues in test files.
  find_files="test" _pipe_files_to_cli $pylint --disable=duplicate-code
}

function code:check() {
  # Find linting issues.
  callback="code:check:non_tests" step Linting non-test files
  callback="code:check:tests" step Linting test files
  return $exit_code
}

function migrations:check() {
  # Check no pending Django migrations.
  # https://docs.djangoproject.com/en/4.2/ref/django-admin/#django-admin-makemigrations
  echo_and_run_cmd $django makemigrations --check --dry-run
}

function test() {
  # Run tests.
  echo_and_run_cmd $pytest $(_make_pytest_options "$@ $source")
}

function test:coverage:report() {
  # Run tests and generate coverage report.
  coverage=1 test --cov-report=xml:coverage.xml
}

function test:coverage:check() {
  # Run tests and check coverage thresholds.
  coverage=1 test --cov-fail-under=90
}

function test:coverage() {
  if github_repo_owner_is_ocado_tech; then
    test:coverage:report $@
  else
    test:coverage:check $@
  fi
}

function packages:check() {
  snyk:test --command=.venv/bin/python --policy-path="$backend_dir/.snyk"
}

function run:django() {
  # Run a local Django server.
  callback="setup" step Setting up PY environment
  function callback() {
    SERVER_MODE="django" echo_and_run_cmd \
      $django runserver localhost:${SERVICE_PORT:-"8000"}
  }
  step Running Django development server
  return $exit_code
}

function check() {
  # Run all checks.
  callback="setup" step Setting up PY environment
  callback="imports:check" step Checking imports
  callback="format:check" step Checking format
  callback="types:check" step Checking types
  callback="code:check" step Checking code
  callback="migrations:check" step Checking Django migrations
  callback="test" step Running tests
  if eval_bool "${packages:-0}"; then
    callback="packages:check" step Checking packages
  fi
  return $exit_code
}

# ------------------------------------------------------------------------------
# Entrypoint
# ------------------------------------------------------------------------------

# Must be the last line in the script!
eval "$(.workspace/.scripts/main run_script $(readlink -f "$0") $@)"
