name: "Code for Life - Git - Add, Commit and Push"
description: "Git add and, if there are differences, commit and push."
inputs:
  add:
    description: "The changes to add."
    required: true
  commit-message:
    description: "The commit message. Prepended with 'chore: ' and post-pended with ' [skip ci]'."
    required: true
  setup-bot:
    description: "A flag designating whether to set up cfl-bot as the git user."
    required: false
    default: "true"
outputs:
  sha:
    description: "The latest commit SHA."
    value: ${{ steps.commit-and-push.outputs.sha }}
runs:
  using: composite
  steps:
    - name: 🤖 Set up CFL Bot
      if: inputs.setup-bot == 'true'
      uses: ocadotechnology/codeforlife-workspace/.github/actions/git/setup-bot@main

    - name: ➕ Git Add
      shell: bash
      run: git add ${{ inputs.add }}

    - name: 🔄 Git Commit and Push
      id: commit-and-push
      shell: bash
      run: |
        # Only commit and push if there are differences.
        sha="$GITHUB_SHA"
        if ! git diff --staged --quiet; then
          git commit -m "chore: ${{ inputs.commit-message }} [skip ci]"
          git push
          sha="$(git rev-parse HEAD)"
        fi

        echo "sha=$sha" >> $GITHUB_OUTPUT
