name: "Code for Life - Git - Add, Commit and Push"
description: "Git add and, if there are differences, commit and push."
inputs:
  cfl-bot-gh-token:
    description: "The GitHub token of the CFL bot."
    required: true
  repository:
    description: "The repository to push to, in the format 'owner/repo'."
    required: true
    default: ${{ github.repository }}
  add:
    description: "The changes to add."
    required: true
  commit-message:
    description: "The commit message. Prepended with 'chore: ' and post-pended with ' [skip ci]'."
    required: true
outputs:
  sha:
    description: "The latest commit SHA."
    value: ${{ steps.commit-and-push.outputs.sha }}
runs:
  using: composite
  steps:
    - shell: bash
      run: git remote set-url origin https://x-access-token:${{ inputs.cfl-bot-gh-token }}@github.com/${{ inputs.repository }}.git

    - name: ➕ Git Add
      shell: bash
      run: git add ${{ inputs.add }}

    - name: 🔄 Git Commit and Push
      id: commit-and-push
      shell: bash
      run: |
        # Only commit and push if there are differences.
        sha="$GITHUB_SHA"
        if ! git diff --staged --quiet; then
          git commit -m "chore: ${{ inputs.commit-message }} [skip ci]"
          git push
          sha="$(git rev-parse HEAD)"
        fi

        echo "sha=$sha" >> $GITHUB_OUTPUT
