name: "Code for Life - Git - Add, Commit and Push"
description: "Git add and, if there are differences, commit and push."
inputs:
  add:
    description: "The changes to add."
    required: true
  commit-message:
    description: "The commit message. Prepended with 'chore: ' and post-pended with ' [skip ci]'."
    required: true
  setup-bot:
    description: "A flag designating whether to set up cfl-bot as the git user."
    required: false
    default: "true"
  force:
    description: "A flag designating whether to force push."
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: 🤖 Set up CFL Bot
      if: inputs.setup-bot == 'true'
      uses: ocadotechnology/codeforlife-workspace/.github/actions/git/setup-bot@main

    - name: ➕ Git Add
      shell: bash
      run: git add ${{ inputs.add }}

    - name: 🔄 Git Commit and Push
      shell: bash
      run: |
        # Only commit and push if there are differences.
        if ! git diff --staged --quiet; then
          git commit -m "chore: ${{ inputs.commit-message }} [skip ci]"
          if [ "${{ inputs.force }}" = "true" ]; then
            git push --force
          else
            git push
          fi
        fi
