name: "Code for Life - Workspace - Download File"
description: "Download a file from the workspace."
inputs:
  branch:
    description: "The branch on the workspace repo."
    required: true
    default: "main"
  path:
    description: "The path of the file."
    required: true
  save-to:
    description: "Where to save the file."
    required: true
runs:
  using: composite
  steps:
    - name: 📥 Download File
      shell: bash
      run: wget https://raw.githubusercontent.com/ocadotechnology/codeforlife-workspace/refs/heads/${{ inputs.branch }}/${{ inputs.path }} -O ${{ inputs.save-to }}
