name: "Code for Life - GitHub - Get Latest Release Tag"
description: "Get the latest release tag from a GitHub repo."
inputs:
  repo:
    description: "The GitHub repo to get the latest release tag from."
    required: false
    default: ${{ github.repository }}
outputs:
  latest-release-tag:
    description: "The latest release tag from the GitHub repo."
    value: ${{ steps.get-latest-release-tag.outputs.value }}
runs:
  using: composite
  steps:
    - name: 🗂️ Get Latest Release Tag
      id: get-latest-release-tag
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        value=$(
          gh release list \
            --exclude-drafts \
            --exclude-pre-releases \
            --repo=${{ inputs.repo }} \
            --limit=1 \
            --json=name \
            --jq=.[0].name
        )

        echo "Outputting: $value"
        echo "value=$value" >> "$GITHUB_OUTPUT"
