name: "Code for Life - Git - Commit and Push"
description: "Git commit and push if changes are found at a path."
inputs:
  add:
    description: "The changes to add."
    required: true
  commit-message:
    description: "The commit message. Prepended with 'chore: ' and post-pended with ' [skip ci]'."
    required: true
runs:
  using: composite
  steps:
    - name: ➕ Git Add
      shell: bash
      run: git add ${{ inputs.add }}

    - name: 🔄 Git Commit and Push
      # if: if ! git diff --staged --quiet
      shell: bash
      run: |
        # Only commit and push if there are differences.
        if ! git diff --staged --quiet; then
          git commit -m "chore: ${{ inputs.commit-message }} [skip ci]"
          git push
        fi
