name: "Code for Life - Git - Checkout"
description: "Git checkout a repository."
inputs:
  repository:
    description: "Repository name with owner."
    required: false
    default: ${{ github.repository }}
  token:
    description: "Personal access token (PAT) used to fetch the repository."
    required: false
    default: ${{ github.token }}
  fetch-depth:
    description: "Number of commits to fetch."
    required: false
    default: "1"
  ref:
    description: "The branch, tag or SHA to checkout."
    required: false
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository."
    required: false
  submodules:
    description: "Whether to checkout submodules."
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: 🛫 Checkout
      uses: actions/checkout@v5
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        submodules: ${{ inputs.submodules }}

    - name: 🔄 Replace Workspace Symlink with Directory
      if: hashFiles(.workspace) != ''
      shell: bash
      run: rm -f .workspace && mkdir .workspace
