name: "Code for Life - Service - Release"
description: "Release a service deployment to GitHub."
inputs:
  cfl-bot-gh-token:
    description: "The GitHub token of the CFL bot."
    required: true
  rc-path:
    description: "The path of the .releaserc.json to use."
    required: true
runs:
  using: composite
  steps:
    - name: 📥 Download Release Candidate Configuration
      uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-config-file@main
      with:
        path: ${{ inputs.rc-path }}
        save-to: .releaserc.json

    - name: 🚀 Publish Semantic Release
      uses: ocadotechnology/codeforlife-workspace/.github/actions/github/release@main
      with:
        cfl-bot-gh-token: ${{ inputs.cfl-bot-gh-token }}
        checkout: false
