name: "Code for Life - Python - Setup Environment"
description: "Set up a python environment."
inputs:
  checkout:
    description: "A flag to designate if the code should be checked out."
    required: true
    default: "true"
  python-version:
    description: "The python version to set up."
    required: true
    default: "3.12"
  install-args:
    description: "Arguments to pass to pipenv install."
    required: false
  workspace-ref:
    description: "The branch, tag or SHA of the workspace to checkout."
    required: false
    default: "main"
runs:
  using: composite
  steps:
    - name: 🛫 Checkout
      if: inputs.checkout == 'true'
      uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/checkout-submodule-and-workspace@main
      with:
        workspace-ref: ${{ inputs.workspace-ref }}

    - name: 🐍 Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: ⬆️ Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: 🛠 Install pipenv
      shell: bash
      run: |
        python -m pip install "$(
          cat .workspace/.devcontainer/devcontainer.json |
          npx strip-json-comments-cli |
          jq -r '
            .features["ghcr.io/devcontainers/features/python:1"].toolsToInstall
          '
        )"

    - name: 🛠 Install Dependencies
      shell: bash
      run: pipenv install ${{ inputs.install-args }}
