name: "Code for Life - Python - Setup Environment"
description: "Set up a python environment."
inputs:
  checkout:
    description: "A flag to designate if the code should be checked out."
    required: true
    default: "true"
  python-version:
    description: "The python version to set up."
    required: true
    default: "3.8"
  working-directory:
    description: "The current working directory."
    required: true
    default: "."
  install-args:
    description: "Arguments to pass to pipenv install."
    required: false
runs:
  using: composite
  steps:
    - name: 🛫 Checkout
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: 🐍 Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: ⬆️ Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: 🛠 Install pipenv
      shell: bash
      run: python -m pip install pipenv

    - name: 🛠 Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pipenv install ${{ inputs.install-args }}
