name: "Code for Life - ESLint - Check Code"
description: "Download ESLint's config file and run ESLint to check the code."
inputs:
  download-branch:
    description: "The branch of the workspace repo to download the config file from."
    required: true
    default: "main"
  save-dir:
    description: "The directory to save the config file to."
    required: true
    default: ".workspace"
  scripts-path:
    description: "The path to the scripts bash file."
    required: true
    default: "./scripts"
runs:
  using: composite
  steps:
    - name: 📥 Download TypeScript Config File
      uses: ocadotechnology/codeforlife-workspace/.github/actions/eslint/download-config@main
      with:
        download-branch: ${{ inputs.download-branch }}
        save-dir: ${{ inputs.save-dir }}

    - name: 🔎 Check Code Types
      shell: bash
      run: ${{ inputs.scripts-path }} code:check
