name: "Code for Life - JavaScript - Setup Environment"
description: "Set up a JavaScript environment."
inputs:
  checkout:
    description: "A flag to designate if the code should be checked out."
    required: true
    default: "true"
  node-version:
    description: "The Node.js version to set up."
    required: true
    default: "22"
  working-directory:
    description: "The current working directory."
    required: true
    default: "."
  install-args:
    description: "Arguments to pass to pipenv install."
    required: false
  workspace-package:
    description: "A flag designating to install the workspace package.json."
    required: false
    default: "true"
  workspace-package-download-branch:
    description: "The branch to download the package.json from the workspace repo."
    required: false
    default: "main"
  gh-token:
    description: "The Personal access token (PAT) used to checkout the repository."
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: 🛫 Checkout
      if: inputs.checkout == 'true'
      uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/checkout-submodule-and-workspace@main
      with:
        token: ${{ inputs.gh-token }}

    - name: 🌐 Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: ⬆️ Upgrade npm
      shell: bash
      run: npm install --global npm

    - name: 🛠 Install Yarn
      shell: bash
      run: npm install --global yarn

    - name: 🛠 Install Workspace Dependencies
      if: inputs.workspace-package == 'true'
      shell: bash
      working-directory: .workspace/frontend
      run: yarn install

    - name: 🛠 Install Submodule Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn install ${{ inputs.install-args }}
