name: "Code for Life - JavaScript - Setup Environment"
description: "Set up a JavaScript environment."
inputs:
  checkout:
    description: "A flag to designate if the code should be checked out."
    required: true
    default: "true"
  node-version:
    description: "The Node.js version to set up."
    required: true
    default: "22"
  install-prod:
    description: "A flag designating whether to install only the production dependencies."
    required: false
    default: "true"
  gh-token:
    description: "The Personal access token (PAT) used to checkout the repository."
    required: false
    default: ${{ github.token }}
  workspace-ref:
    description: "The branch, tag or SHA of the workspace to checkout."
    required: false
    default: "main"
runs:
  using: composite
  steps:
    - name: 🛫 Checkout
      if: inputs.checkout == 'true'
      uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/checkout-submodule-and-workspace@main
      with:
        token: ${{ inputs.gh-token }}
        workspace-ref: ${{ inputs.workspace-ref }}

    - name: 🌐 Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: ⬆️ Upgrade npm
      shell: bash
      run: npm install --global npm

    - name: 🛠 Install Yarn
      shell: bash
      run: npm install --global yarn

    - name: 🛠 Install Workspace Dependencies
      if: inputs.install-prod == 'false'
      shell: bash
      working-directory: .workspace/frontend
      run: yarn install

    - name: 🛠 Install Submodule Dependencies
      shell: bash
      run: yarn install --production=${{ inputs.install-prod }}
