name: "Code for Life - JavaScript - Setup Environment"
description: "Set up a JavaScript environment."
inputs:
  checkout:
    description: "A flag to designate if the code should be checked out."
    required: true
    default: "true"
  node-version:
    description: "The Node.js version to set up."
    required: true
    default: "22"
  working-directory:
    description: "The current working directory."
    required: true
    default: "."
  install-args:
    description: "Arguments to pass to pipenv install."
    required: false
  workspace-package:
    description: "A flag designating to install the workspace package.json."
    required: false
    default: "true"
  workspace-package-download-branch:
    description: "The branch to download the package.json from the workspace repo."
    required: false
    default: "main"
runs:
  using: composite
  steps:
    - name: 🛫 Checkout
      if: inputs.checkout == 'true'
      uses: actions/checkout@v4

    - name: 📥 Download Workspace package.json
      if: inputs.workspace-package == 'true'
      uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.workspace-package-download-branch }}
        path: configs/frontend/package.json
        save-to: .workspace/package.json

    - name: 📥 Download Workspace yarn.lock
      if: inputs.workspace-package == 'true'
      uses: ocadotechnology/codeforlife-workspace/.github/actions/workspace/download-file@main
      with:
        branch: ${{ inputs.workspace-package-download-branch }}
        path: configs/frontend/yarn.lock
        save-to: .workspace/yarn.lock

    - name: ✏️ Write Path to Workspace package.json
      if: inputs.workspace-package == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "$(
          jq '
            .devDependencies["@codeforlife/workspace"] = "link:.workspace"
          ' package.json
        )" > package.json

    - name: 🌐 Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: ⬆️ Upgrade npm
      shell: bash
      run: npm install --global npm

    - name: 🛠 Install Yarn
      shell: bash
      run: npm install --global yarn

    - name: 🛠 Install Workspace Dependencies
      if: inputs.workspace-package == 'true'
      shell: bash
      working-directory: .workspace
      run: yarn install

    - name: 🛠 Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: yarn install ${{ inputs.install-args }}
