#!/bin/bash

set -e

function configure_labels() {
  local repo_name="$1"

  echo_h1 "$repo_name"

  local repo="$(make_repo "$repo_name")"

  local index=1

  while read -r label; do
    local name="$(echo "$label" | jq -r '.key')"
    local colour="$(echo "$label" | jq -r '.value.colour')"
    local description="$(echo "$label" | jq -r '.value.description')"

    options="-n" echo_bold "($index/$labels_length)."
    index=$((index + 1))
    echo -n " \"$name\" "

    local all_outputs=$(
      gh label create "$name" \
        --repo="$repo" \
        --color="$colour" \
        --description="$description" \
        --force \
        2>&1
    )

    if [ $? -eq 0 ]; then
      echo_success "✔"
    else
      exit_code=1
      echo_error "✗\n$all_outputs"
    fi
  done < <(echo "$labels" | jq -c 'to_entries | .[]')
}

exit_code=0

check_labels_descriptor

labels="$(get_labels_from_descriptor)"
labels_length="$(echo "$labels" | jq 'length')"
echo_info "Discoverd $labels_length labels."

if [ "$labels_length" -gt 0 ]; then
  configure_labels "$REPO_NAME"
  process_workspace_submodules "configure_labels"
fi

exit $exit_code
