name: "Code for Life - Git - Setup Bot"
description: "Sets up CFL's bot as the Git user."
runs:
  using: composite
  steps:
    - name: 🤖 Set up cfl-bot as Git user
      shell: bash
      run: |
        git config --local user.name cfl-bot
        git config --local user.email codeforlife-bot@ocado.com
