name: "Code for Life - Service - Release"
description: "Release a service deployment to GitHub."
inputs:
  cfl-bot-gh-token:
    description: "The GitHub token of the CFL bot."
    required: true
  deploy-artifact-path:
    description: "The path of the deploy artifact."
    required: false
    default: ".deploy"
  deploy-zip-path:
    description: "The path of the deploy.zip."
    required: false
    default: "../deploy.zip"
runs:
  using: composite
  steps:
    - name: 🛫 Checkout
      uses: ocadotechnology/codeforlife-workspace/.github/actions/git/checkout@main
      with:
        token: ${{ inputs.cfl-bot-gh-token }}
        fetch-depth: 0

    - name: 📁 Zip Deploy Files
      shell: bash
      run: |
        if [ -d ${{ inputs.deploy-artifact-path }} ]; then
          cd ${{ inputs.deploy-artifact-path }}
          zip --quiet --recurse-paths ${{ inputs.deploy-zip-path }} .
        fi

    - name: 📁 Zip Dotenv Files
      shell: bash
      run: zip --quiet --recurse-paths env.zip env
