#!/bin/bash

# The ID of the Ocado Technology GitHub organization.
# https://github.com/ocadotechnology
ocado_tech_org_id=${OCADO_TECH_ORG_ID:-2088731}

function github_repo_owner_is_ocado_tech() {
  if [ "$GITHUB_REPOSITORY_OWNER_ID" -eq $ocado_tech_org_id ]; then
    return 0
  else
    return 1
  fi
}

function handle_event() {
  if [ -z "$EVENT_NAME" ]; then
    exit=1 echo_error "Event name not defined."
  fi

  "handle_${EVENT_NAME}_event" "$@"
}
