name: "Code for Life - Workspace - Download And Run Job Script"
description: "Download a job script from the workspace and run it."
inputs:
  args:
    description: "The arguments to pass to the script."
    required: false
    default: ""
  workflow:
    description: "The path of the workflow. Required if a workflow is called by another."
    required: true
    default: "${{ github.workflow_ref }}"
  job:
    description: "The name of the job. Required if a workflow is called by another."
    required: true
    default: "${{ github.job }}"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        scripts_path=".scripts/__main__"
        if [[ -d .workspace ]]; then scripts_path=".workspace/$scripts_path"; fi
        $scripts_path run_workflow_job_script "${{ inputs.workflow }} ${{ inputs.job }} ${{ inputs.args }}"
