name: "Code for Life - Workspace - Download And Run Job Script"
description: "Download a job script from the workspace and run it."
inputs:
  args:
    description: "The arguments to pass to the script."
    required: false
    default: ""
  workflow:
    description: "The path of the workflow. Required if a workflow is called by another."
    required: true
    default: "${{ github.workflow_ref }}"
  job:
    description: "The name of the job. Required if a workflow is called by another."
    required: true
    default: "${{ github.job }}"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        repository: ocadotechnology/codeforlife-workspace

    - shell: bash
      run: .scripts/__main__ run_workflow_job_script "${{ inputs.workflow }} ${{ inputs.job }} ${{ inputs.args }}"
