name: "Code for Life - Workspace - Checkout Submodule and Workspace"
description: "Checkout a submodule and replace the .workspace symlink in it with a checkout of the workspace."
inputs:
  token:
    description: "Personal access token (PAT) used to fetch the repository."
    required: false
    default: ${{ github.token }}
  fetch-depth:
    description: "Number of commits to fetch."
    required: false
    default: "1"
  ref:
    description: "The branch, tag or SHA to checkout."
    required: false
  workspace-ref:
    description: "The branch, tag or SHA of the workspace to checkout."
    required: false
    default: "main"
runs:
  using: composite
  steps:
    - name: 🛫 Checkout Submodule
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}

    - name: 🗑️ Remove Workspace Symlink
      shell: bash
      run: if [ -L .workspace ]; then rm .workspace; fi

    - name: 🛫 Checkout Workspace
      uses: actions/checkout@v5
      with:
        repository: ocadotechnology/codeforlife-workspace
        path: .workspace
        submodules: false
        ref: ${{ inputs.workspace-ref }}
