name: "Code for Life - GitHub - Process String Array"
description: "Process each value in a string array."
inputs:
  strings:
    description: "The array of strings to process."
    required: true
  delimiter:
    description: "What characters to split the strings on."
    required: true
    default: "$','" # newline or comma
  process_string:
    description: "A callback which processes each string in the array."
    required: true
runs:
  using: composite
  steps:
  - name: ⚙️ Process String Array
    shell: bash
    run: |
      # A callback to process each string.
      process_string() {
        ${{ inputs.process_string }}
      }

      # Function to trim whitespace
      trim() {
        echo "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
      }

      # Use a here-string to feed the string to the while loop
      echo "${{ inputs.strings }}" | while IFS="${{ inputs.delimiter }}" read -r line; do
        # Split the line into individual values
        IFS="${{ inputs.delimiter }}" read -ra values <<<"$line"

        # Iterate through the values and call the callback for each
        for value in "${values[@]}"; do
          trimmed_value=$(trim "$value")
          if [ "$trimmed_value" != "" ]; then
            process_string "$trimmed_value"
          fi
        done
      done
