#!/bin/bash

function eval_bool() {
  local bool="$1"

  bool=$(echo "$bool" | tr '[:upper:]' '[:lower:]')

  if [ "$bool" = "1" ] || [ "$bool" = "true" ] || [ "$bool" = "t" ]; then
    return 0
  elif [ "$bool" = "0" ] || [ "$bool" = "false" ] || [ "$bool" = "f" ]; then
    return 1
  fi

  exit=1 echo_error "Attempted to evaluate invalid boolean value: \"$bool\"."
}

function csv_to_array() {
  local csv="$1"
  local -n array="$2"

  read -r -a array < <(echo "$csv" | tr "," " ")
}

function in_array() {
  local search="$1"

  for item in "${@:2}"; do
    if [ "$item" = "$search" ]; then return 0; fi
  done

  return 1
}

function trim_spaces() {
  echo -n "$@" |
    sed --expression ':a;N;$!ba;s/^\n*//;s/\n*$//' |
    sed --regexp-extended 's/^[[:space:]]*|[[:space:]]*$//g'
}

function echo_cmd() {
  local cmd="$ $@"
  if [ "$CI" = "true" ]; then
    echo "$cmd"
  else
    echo -e "${BLACK}$cmd${RESET}"
  fi
}

function echo_and_run_cmd() {
  echo_cmd "$@"
  $@
}
