#!/bin/bash

# General bash utilities to be used across the whole workspace.

function import_workspace_script() { source .workspace/.scripts/$1; }

import_workspace_script ansi
import_workspace_script general
import_workspace_script github
import_workspace_script run
import_workspace_script snyk

$@ # Entrypoint. Must be the last line in the script!
