name: "Code for Life - Codecov - Upload Report"
description: "Upload a coverage report to Codecov."
inputs:
  token:
    description: "The token used to gain access to Codecov."
    required: true
  files:
    description: "A CSV of the paths of the coverage files to upload."
    required: true
runs:
  using: composite
  steps:
    - name: 📈 Upload Coverage Reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ inputs.token }}
        slug: ${{ github.repository }}
        codecov_yml_path: .workspace/codecov.yml
        files: ${{ inputs.files }}
