name: "Code for Life - Vite - Run Tests"
description: "Download Vite's config file and run Vitest to run the tests."
inputs:
  download-config:
    description: "A flag designating whether to download the config file."
    required: true
    default: "true"
  download-branch:
    description: "The branch of the workspace repo to download the config file from."
    required: true
    default: "main"
  save-dir:
    description: "The directory to save the config file to."
    required: true
    default: ".workspace"
  scripts-path:
    description: "The path to the scripts bash file."
    required: true
    default: "./scripts"
  ocado-tech-org-id:
    description: "The ID of the Ocado Tech GitHib organization."
    required: true
    default: "2088731"
  codecov-token:
    description: "The token used to upload coverage reports to Codecov."
    required: false
runs:
  using: composite
  steps:
    - name: 📥 Download Vite Config File
      if: inputs.download-config == 'true'
      uses: ocadotechnology/codeforlife-workspace/.github/actions/vite/download-config@main
      with:
        download-branch: ${{ inputs.download-branch }}
        save-dir: ${{ inputs.save-dir }}

    - name: 🧪 Test Code
      shell: bash
      run: |
        if [ ${{ github.repository_owner_id }} = ${{ inputs.ocado-tech-org-id }} ]; then
          ${{ inputs.scripts-path }} test:coverage:report
        else
          ${{ inputs.scripts-path }} test:coverage:check
        fi

    - name: 📈 Upload Coverage Reports to Codecov
      if: github.repository_owner_id == inputs.ocado-tech-org-id
      uses: ocadotechnology/codeforlife-workspace/.github/actions/codecov/upload-report@main
      with:
        config-download-branch: ${{ inputs.download-branch }}
        config-path: ${{ inputs.save-dir }}/codecov.yml
        token: ${{ inputs.codecov-token }}
        file: coverage/cobertura-coverage.xml
