name: Configure Submodules

on:
  push:
    branches:
      - main
    paths:
      - '.submodules/**'
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11
      WORKING_DIR: .submodules
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 🐍 Set up Python ${{ env.PYTHON_VERSION }} Environment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/python/setup-environment@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          working-directory: ${{ env.WORKING_DIR }}

      - uses: ocadotechnology/codeforlife-workspace/.github/actions/git/setup-bot@main

      - name: ⚙️ Configure Submodules
        working-directory: ${{ env.WORKING_DIR }}
        run: pipenv run python .
        env:
          GIT_PUSH_CHANGES: '0' # TODO: set to 1 and allow bot to force push
