name: Monitor JavaScript Release

on:
  workflow_call:
    inputs:
      node-version:
        description: "The Node.js version to set up."
        type: number
        required: true
      remove-repo-name-prefix:
        description: "The prefix to remove from the repo's name."
        type: string
        required: false
        default: "codeforlife-"
    secrets:
      CFL_APP_PRIVATE_KEY:
        description: "The private key of CFL's GitHub App."
        required: true
      SNYK_TOKEN:
        description: "The token used to authenticate with Snyk API."
        required: true

jobs:
  monitor:
    concurrency: release
    runs-on: ubuntu-22.04
    steps:
      - name: 🤖 Set up CFL bot
        uses: ocadotechnology/codeforlife-workspace/.github/actions/bot/setup@main
        id: setup-bot
        with:
          cfl-app-private-key: ${{ secrets.CFL_APP_PRIVATE_KEY }}

      - name: 🌐 Set up JavaScript ${{ inputs.node-version }} Environment
        uses: ocadotechnology/codeforlife-workspace/.github/actions/javascript/setup-environment@main
        with:
          node-version: ${{ inputs.node-version }}
          checkout-workspace: false

      - name: 🔎 Monitor Open-Source Vulnerabilities and License Issues
        uses: ocadotechnology/codeforlife-workspace/.github/actions/snyk/monitor-release@main
        with:
          gh-token: ${{ steps.setup-bot.outputs.token }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          snyk-config-path: frontend/.snyk
          snyk-project-environment: frontend
          snyk-add-monitor-args: --package-manager=yarn
          remove-repo-name-prefix: ${{ inputs.remove-repo-name-prefix }}
