name: Validate Pull Request

on:
  workflow_call:
    inputs:
      number:
        required: true
        type: number
      review-state:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true

env:
  PYTHON_VERSION: 3.11
  WORKING_DIR: .github/scripts/python/validate-pull-request

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: ocadotechnology/codeforlife-workspace/.github/actions/python/setup-environment@new_contributor_validations # TODO: use @main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          working-directory: ${{ env.WORKING_DIR }}

      - name: 🕵️ Validate Pull Request
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
        run: pipenv run python .
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NUMBER: ${{ inputs.number }}
          REVIEW_STATE: ${{ inputs.review-state }}
